spring.application.name=fitnessapp
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
spring.datasource.url=jdbc:mysql://localhost:3306/fitnessapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Chris7588!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8100

